title: Bulk Delete Annotations
description: This AddOn runs through all documents either selected or queried and deletes the annotations for documents. 
type: object
documents:
  - query
  - selected
properties: {}
version: 2
