title: Bulk Delete Annotations
description: This AddOn runs through all documents either selected or queried and deletes the annotations for documents. 
instructions: ''
type: object
documents:
  - query
  - selected
properties: {}
version: 2
categories:
  - bulk
